@host = http://localhost:4000

###
POST {{host}}/servicio/create
Content-Type: application/json

{
    "SERVICIO": "TRATAMIENTO DE CUIDADO",
    "PRECIO_S": "200"
}

###
GET {{host}}/servicios/all
Content-Type: application/json

###
GET {{host}}/servicio/2
Content-Type: application/json

###
PUT {{host}}/servicioupd/2
Content-Type: application/json

{
    "SERVICIO": "TRATAMIENTO DE CUIDADO",
    "PRECIO_S": "200"
}

